### ISSUE TITLE
Use different color scheme to export PDFs

### ISSUE THREAD

**Issue by fengtality** [adrienbrignon/mkdocs-exporter#15]
Suggestion: add a flag that lets users select certain color scheme

For instance, my site defaults to the `slate` (dark theme) but ideally I'd like the PDF exporter to use the `default` (light) theme in generating documents

```
theme:
  palette:
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
```

**Comment by adrienbrignon** [comment]
Hello @fengtality,

The light mode seems to be enforced when printing, based on [the *SCSS* defined by *MkDocs Material*](https://github.com/squidfunk/mkdocs-material/blob/0b38323a310d9ab9ac7fd60ad0bdae5871e42d73/src/templates/assets/stylesheets/palette/_scheme.scss#L27).

Now, concerning the accent colors not being respected, the issue seems to be coming from *Paged.js* after a quick look. I'll investigate further and provide a solution.

In the meantime, you may be able to override the [*CSS variables*](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) used by *MkDocs Material* during the rendering process (using the `stylesheets` property of the `exporter-pdf` plugin).

For instance, [this documentation uses](https://github.com/adrienbrignon/mkdocs-exporter/blob/33db06ac6aa755f8f039ff1ba25dff15afc351da/docs/assets/stylesheets/custom.css#L1C1-L4C2):

```scss
:root {
  --md-primary-fg-color: #EA2027;
  --md-accent-fg-color: #000000;
}
```
