### ISSUE TITLE
playwright._impl._errors.TimeoutError: Locator.wait_for: Timeout 60000ms exceeded.

### ISSUE THREAD

**Issue by PhilStollery50Hertz** [adrienbrignon/mkdocs-exporter#36]
Producing a 150 page PDF with covers is causing a timeout issue. Is there a way to increare the playwright timeout in config?

**Comment by PhilStollery50Hertz** [comment]
If I remove the covers it works.

**Comment by adrienbrignon** [comment]
Hello @PhilStollery50Hertz,

You should be able to increase the timeout (which defaults to `60000` milliseconds) by using the [`formats.pdf.browser.timeout`](https://adrienbrignon.github.io/mkdocs-exporter/reference/configuration/formats/pdf/#mkdocs_exporter.formats.pdf.config.BrowserConfig.timeout) option.

Don't hesitate to reach out with any updates on the issue.

**Comment by PhilStollery** [comment]
> Hello @PhilStollery50Hertz,
> 
> You should be able to increase the timeout (which defaults to `60000` milliseconds) by using the [`formats.pdf.browser.timeout`](https://adrienbrignon.github.io/mkdocs-exporter/reference/configuration/formats/pdf/#mkdocs_exporter.formats.pdf.config.BrowserConfig.timeout) option.
> 
> Don't hesitate to reach out with any updates on the issue.

Where / how do I change the config when using the docker image? So I build with CI/CD and can't change the source.

**Comment by adrienbrignon** [comment]
> > Hello @PhilStollery50Hertz,
> > You should be able to increase the timeout (which defaults to `60000` milliseconds) by using the [`formats.pdf.browser.timeout`](https://adrienbrignon.github.io/mkdocs-exporter/reference/configuration/formats/pdf/#mkdocs_exporter.formats.pdf.config.BrowserConfig.timeout) option.
> > Don't hesitate to reach out with any updates on the issue.
> 
> Where / how do I change the config when using the docker image? So I build with CI/CD and can't change the source.

You can change the configuration by editing the `mkdocs.yml` file directly from your repository.

**Comment by PhilStollery** [comment]
I tried to add one:

WARNING -  Config value 'plugins': Plugin 'exporter' option 'formats': Sub-option 'pdf': Sub-option 'timeout': Unrecognised
           configuration name: timeout

My config:

plugins:
  - exporter:
      logging:
        level: debug
      timeout: 120000
      formats:
        pdf:
          enabled: true
          explicit: true
          concurrency: 16
          stylesheets:
            - docs/stylesheets/pdf.scss
          aggregator:
            enabled: false
            output: reference_architecture.pdf
            covers: all
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes

**Comment by adrienbrignon** [comment]
Here's an updated version of your configuration that should work:

```yaml
plugins:
  - exporter:
      logging:
        level: debug
      formats:
        pdf:
          enabled: true
          explicit: true
          concurrency: 16
		  browser:
		    timeout: 120000
          stylesheets:
            - docs/stylesheets/pdf.scss
          aggregator:
            enabled: false
            output: reference_architecture.pdf
            covers: all
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
```

Don't hesitate to reach out with any updates on the issue.
