### ISSUE TITLE
Jinja Variables not Replaced with Values

### ISSUE THREAD

**Issue by scaui0** [adrienbrignon/mkdocs-exporter#57]
In cover pages jinja variables like `{{ cong.site_name }}` are not replaced woth their corresponding value.
I think it's not an configuration error, because with the official documantation of mkdocs-exporter it even deosn't work.

Kind regards
scaui0

**Comment by nbanyan** [comment]
The Jinja for the cover pages is handled by the macros plugin.

```
plugins:
  - exporter
  - macros
```

If you have Jinja-like text in your site's pages, you can tell macros to use a custom syntax.

```
plugins:
  - exporter
  - macros:
      j2_block_start_string: '〘%'
      j2_block_end_string: '%〙'
      j2_variable_start_string: '〘〘'
      j2_variable_end_string: '〙〙'
      j2_comment_start_string: '〘#'
      j2_comment_end_string: '#〙'
```
