### ISSUE TITLE
how does one enable page numbers like in your sample pdfs?

### ISSUE THREAD

**Issue by milkshakeuk** [adrienbrignon/mkdocs-exporter#66]
see title

**Comment by milkshakeuk** [comment]
I figured it out

```scss
@page {
  size: A4;
  margin: 1.20cm;

  @bottom-center {
    content: "Page " counter(page) " of " counter(pages);
  }
}

```
