### ISSUE TITLE
Config value 'plugins': Invalid config options for the 'mkdocs/exporter' plugin.

### ISSUE THREAD

**Issue by JayaramaKrishnaGudipati** [adrienbrignon/mkdocs-exporter#7]
Hi @adrienbrignon,

Hope you remember me, I worked with you for a get_evet_loop issue few weeks back.
I upgraded the plugin version to 3.0.3 and I was using the same mkdocs file given below, I'm receiving the "invalid config" error, please let me know if any other plugin configurations I have to add here in the file,

```
plugins:
  mkdocs/exporter:
    theme:'material'
  mkdocs/exporter/pdf:
    concurrency: 8
    covers:
      front: resources/templates/covers/front.html.j2
      back: resources/templates/covers/back.html.j2
    stylesheets:
      - resources/stylesheets/pdf.scss
  mkdocs/exporter/extras:
    buttons:
      - title: Download as PDF
        enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
        icon: !!python/name:mkdocs_exporter.plugins.pdf.button.icon
        attributes:
          href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
          download: !!python/name:mkdocs_exporter.plugins.pdf.button.download
```

ERROR    -  Config value 'plugins': Invalid config options for the 'mkdocs/exporter' plugin.
Aborted with 1 Configuration Errors!

Thanks

**Comment by adrienbrignon** [comment]
Hello @JayaramaKrishnaGudipati,

Yes, for sure; thanks again for your contributions to #3.

I guess that the issue here is because your `plugins` option is an object instead of an array (here's the [documentation](https://www.mkdocs.org/dev-guide/plugins/#using-plugins) for reference).
This is what your configuration should look like:

```yaml
plugins:
  - mkdocs/exporter:
      theme:'material'
  - mkdocs/exporter/pdf:
      concurrency: 8
      covers:
        front: resources/templates/covers/front.html.j2
        back: resources/templates/covers/back.html.j2
      stylesheets:
        - resources/stylesheets/pdf.scss
  - mkdocs/exporter/extras:
      buttons:
        - title: Download as PDF
          enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
          icon: !!python/name:mkdocs_exporter.plugins.pdf.button.icon
          attributes:
            href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
            download: !!python/name:mkdocs_exporter.plugins.pdf.button.download
```

**Comment by JayaramaKrishnaGudipati** [comment]
Hi @adrienbrignon ,

Thanks again for responding and supporting on the issue.
I still see the same below error even after changing the plugin to array format as given by you, previously it was working for me when used in object format also, now I see this below error. Could you please let me know the possible causes?

ERROR    -  Config value 'plugins': Invalid config options for the 'mkdocs/exporter' plugin.
Aborted with 1 Configuration Errors!

Thanks

**Comment by adrienbrignon** [comment]
Hi @JayaramaKrishnaGudipati,

I think the problem lies in your config file, not the plugin itself.
Reading your config file, it looks like you forgot to add a space between the `theme` property and its value.

```yaml
plugins:
  - mkdocs/exporter:
      theme:'material'
```

should be written as:

```yaml
plugins:
  - mkdocs/exporter:
      theme: 'material'
```

Could you confirm that adding the missing space resolves your issue, please?

Thanks,

Adrien
