### ISSUE TITLE
Mermaid diagrams are not rendered in exported pdf

### ISSUE THREAD

**Issue by streuspeicher** [adrienbrignon/mkdocs-exporter#71]
I have a document full of mermaid diagrams that are exported as plain text. 
Not sure if this is a bug, if I am doing something wrong or if this is simply not supported. 

requirements.txt: 

```
mkdocs==1.6.1
mkdocs-material==9.6.7
mkdocs-glightbox==0.4.0
mkdocs-exporter==6.2.0
mkdocs-mermaid2-plugin==1.2.1
```

mkdocs.yml (extract): 

```yaml

markdown_extensions:

  # see https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search:
      enabled: true
  - glightbox
  - mermaid2:
      version: 11.4.1
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, false]
          explicit: true
      buttons:
        - title: PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
```

I am willing to contribute if this is a missing feature.
